// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqCAQoORUhlcm9DbGFzc1R5cGUSGQoV",
            "RUhFUk9fQ0xBU1NfVFlQRV9OT05FEAASHQoZRUhFUk9fQ0xBU1NfVFlQRV9H",
            "VUFSRElBThABEhsKF0VIRVJPX0NMQVNTX1RZUEVfQVJDSEVSEAISGQoVRUhF",
            "Uk9fQ0xBU1NfVFlQRV9NQUdFEAMqnQEKEUVDcmVhdGVIZXJvUmVzdWx0EhwK",
            "GEVDUkVBVEVfSEVST19SRVNVTFRfTk9ORRAAEh8KG0VDUkVBVEVfSEVST19S",
            "RVNVTFRfU1VDQ0VTUxABEiQKIEVDUkVBVEVfSEVST19SRVNVTFRfRkFJTF9P",
            "VkVSTEFQEAISIwofRUNSRUFURV9IRVJPX1JFU1VMVF9GQUlMX01JTk1BWBAD",
            "KocBCgtFT2JqZWN0VHlwZRIVChFFT0JKRUNUX1RZUEVfTk9ORRAAEhUKEUVP",
            "QkpFQ1RfVFlQRV9IRVJPEAESGAoURU9CSkVDVF9UWVBFX01PTlNURVIQAhIa",
            "ChZFT0JKRUNUX1RZUEVfRFJPUF9JVEVNEAMSFAoQRU9CSkVDVF9UWVBFX05Q",
            "QxAEKpEBCg5FQ3JlYXR1cmVTdGF0ZRIYChRFQ1JFQVRVUkVfU1RBVEVfSURM",
            "RRAAEhgKFEVDUkVBVFVSRV9TVEFURV9NT1ZFEAESGQoVRUNSRUFUVVJFX1NU",
            "QVRFX1NLSUxMEAISFwoTRUNSRUFUVVJFX1NUQVRFX0RJRRADEhcKE0VDUkVB",
            "VFVSRV9TVEFURV9ISVQQBCrPAQoIRU1vdmVEaXISEgoORU1PVkVfRElSX05P",
            "TkUQABIQCgxFTU9WRV9ESVJfVVAQARIWChJFTU9WRV9ESVJfVVBfUklHSFQQ",
            "AhITCg9FTU9WRV9ESVJfUklHSFQQAxIYChRFTU9WRV9ESVJfUklHSFRfRE9X",
            "ThAEEhIKDkVNT1ZFX0RJUl9ET1dOEAUSFwoTRU1PVkVfRElSX0RPV05fTEVG",
            "VBAGEhIKDkVNT1ZFX0RJUl9MRUZUEAcSFQoRRU1PVkVfRElSX0xFRlRfVVAQ",
            "CCqjAQoQRVNraWxsRmFpbFJlYXNvbhIbChdFU0tJTExfRkFJTF9SRUFTT05f",
            "Tk9ORRAAEhsKF0VTS0lMTF9GQUlMX1JFQVNPTl9TVFVOEAESGwoXRVNLSUxM",
            "X0ZBSUxfUkVBU09OX0RJU1QQAhIbChdFU0tJTExfRkFJTF9SRUFTT05fQ09T",
            "VBADEhsKF0VTS0lMTF9GQUlMX1JFQVNPTl9DT09MEAQqnQIKCUVTdGF0VHlw",
            "ZRITCg9FU1RBVF9UWVBFX05PTkUQABIVChFFU1RBVF9UWVBFX01BWF9IUBAB",
            "EhUKEUVTVEFUX1RZUEVfTUFYX01QEAISEQoNRVNUQVRfVFlQRV9IUBADEhEK",
            "DUVTVEFUX1RZUEVfTVAQBBISCg5FU1RBVF9UWVBFX0FUSxAFEhYKEkVTVEFU",
            "X1RZUEVfREVGRU5DRRAGEhkKFUVTVEFUX1RZUEVfTU9WRV9TUEVFRBAHEhgK",
            "FEVTVEFUX1RZUEVfQVRLX1NQRUVEEAgSJwojRVNUQVRfVFlQRV9BRERfQVRL",
            "X1NQRUVEX01VTFRJUExJRVIQCRIdChlFU1RBVF9UWVBFX0JBU0VfQVRLX1NQ",
            "RUVEEAoqNgoJRU1vdmVUeXBlEhMKD0VNT1ZFX1RZUEVfTk9ORRAAEhQKEEVN",
            "T1ZFX1RZUEVfQ0hBU0UQASpcCg1FTW9uc3RlckdyYWRlEhcKE0VNT05TVEVS",
            "X0dSQURFX05PTkUQABIZChVFTU9OU1RFUl9HUkFERV9OT1JNQUwQARIXChNF",
            "TU9OU1RFUl9HUkFERV9SQVJFEAIqRAoNRVRlbGVwb3J0VHlwZRIXChNFVEVM",
            "RVBPUlRfVFlQRV9OT05FEAASGgoWRVRFTEVQT1JUX1RZUEVfUkVTUEFXThAB",
            "KmIKCUVJdGVtVHlwZRITCg9FSVRFTV9UWVBFX05PTkUQABIUChBFSVRFTV9U",
            "WVBFX0VRVUlQEAESFgoSRUlURU1fVFlQRV9DT05TVU1FEAISEgoORUlURU1f",
            "VFlQRV9FVEMQAyqQAgoORUVxdWlwSXRlbVR5cGUSGQoVRUVRVUlQX0lURU1f",
            "VFlQRV9OT05FEAASGwoXRUVRVUlQX0lURU1fVFlQRV9XRUFQT04QARIbChdF",
            "RVFVSVBfSVRFTV9UWVBFX1NISUVMRBACEhsKF0VFUVVJUF9JVEVNX1RZUEVf",
            "SEVMTUVUEAMSGgoWRUVRVUlQX0lURU1fVFlQRV9BUk1PUhAEEhoKFkVFUVVJ",
            "UF9JVEVNX1RZUEVfQk9PVFMQBRIbChdFRVFVSVBfSVRFTV9UWVBFX0dMT1ZF",
            "UxAGEhwKGEVFUVVJUF9JVEVNX1RZUEVfUEVOREFOVBAHEhkKFUVFUVVJUF9J",
            "VEVNX1RZUEVfUklORxAIKrsCCglFU2xvdFR5cGUSEwoPRVNMT1RfVFlQRV9O",
            "T05FEAASFQoRRVNMT1RfVFlQRV9XRUFQT04QARIVChFFU0xPVF9UWVBFX1NI",
            "SUVMRBACEhUKEUVTTE9UX1RZUEVfSEVMTUVUEAMSFAoQRVNMT1RfVFlQRV9B",
            "Uk1PUhAEEhQKEEVTTE9UX1RZUEVfQk9PVFMQBRIVChFFU0xPVF9UWVBFX0dM",
            "T1ZFUxAGEhYKEkVTTE9UX1RZUEVfUEVOREFOVBAHEhkKFUVTTE9UX1RZUEVf",
            "RklSU1RfUklORxAIEhoKFkVTTE9UX1RZUEVfU0VDT05EX1JJTkcQCRIUChBF",
            "U0xPVF9UWVBFX0VRVUlQEGQSFwoSRVNMT1RfVFlQRV9DT05TVU1FEMgBEhMK",
            "DkVTTE9UX1RZUEVfRVRDEKwCKnEKEUVQaWNrdXBGYWlsUmVhc29uEhwKGEVQ",
            "SUNLVVBfRkFJTF9SRUFTT05fTk9ORRAAEiAKHEVQSUNLVVBfRkFJTF9SRUFT",
            "T05fTk9UX01JTkUQARIcChhFUElDS1VQX0ZBSUxfUkVBU09OX0ZVTEwQAio+",
            "CgxFQWRkSXRlbVR5cGUSFgoSRUFERF9JVEVNX1RZUEVfTkVXEAASFgoSRUFE",
            "RF9JVEVNX1RZUEVfT0xEEAEqPwoLRUl0ZW1TdGF0dXMSFQoRRUlURU1fU1RB",
            "VFVTX05PTkUQABIZChVFSVRFTV9TVEFUVVNfRVFVSVBQRUQQASpeCg9FQ29u",
            "c3VtYWJsZVR5cGUSGQoVRUNPTlNVTUFCTEVfVFlQRV9OT05FEAASFwoTRUNP",
            "TlNVTUFCTEVfVFlQRV9IUBABEhcKE0VDT05TVU1BQkxFX1RZUEVfTVAQAiqf",
            "AQoLRUVmZmVjdFR5cGUSFQoRRUVGRkVDVF9UWVBFX05PTkUQABIXChNFRUZG",
            "RUNUX1RZUEVfREFNQUdFEAESFQoRRUVGRkVDVF9UWVBFX0hFQUwQAhIYChRF",
            "RUZGRUNUX1RZUEVfQUREU1RBVBADEhcKE0VFRkZFQ1RfVFlQRV9TSElFTEQQ",
            "BBIWChJFRUZGRUNUX1RZUEVfQUdHUk8QBSp/ChNFRWZmZWN0RHVyYXRpb25U",
            "eXBlEh4KGkVFRkZFQ1RfRFVSQVRJT05fVFlQRV9OT05FEAASIwofRUVGRkVD",
            "VF9EVVJBVElPTl9UWVBFX1RFTVBPUkFSWRABEiMKH0VFRkZFQ1RfRFVSQVRJ",
            "T05fVFlQRV9QRVJNQU5FTlQQAiqvAQoSRUVmZmVjdFNjYWxpbmdUeXBlEh0K",
            "GUVFRkZFQ1RfU0NBTElOR19UWVBFX05PTkUQABIcChhFRUZGRUNUX1NDQUxJ",
            "TkdfVFlQRV9BVEsQARIbChdFRUZGRUNUX1NDQUxJTkdfVFlQRV9IUBACEh8K",
            "G0VFRkZFQ1RfU0NBTElOR19UWVBFX0VOVElUWRADEh4KGkVFRkZFQ1RfU0NB",
            "TElOR19UWVBFX01BWEhQEAQqUwoKRVNraWxsVHlwZRIUChBFU0tJTExfVFlQ",
            "RV9OT05FEAASFgoSRVNLSUxMX1RZUEVfQUNUSVZFEAESFwoTRVNLSUxMX1RZ",
            "UEVfUEFTU0lWRRACKl4KFEVTa2lsbFByb2plY3RpbGVUeXBlEh8KG0VTS0lM",
            "TF9QUk9KRUNUSUxFX1RZUEVfTk9ORRAAEiUKIUVTS0lMTF9QUk9KRUNUSUxF",
            "X1RZUEVfUFJPSkVDVElMRRABKkgKCEVOUENUeXBlEhIKDkVOUENfVFlQRV9O",
            "T05FEAASEwoPRU5QQ19UWVBFX1NUT1JFEAESEwoPRU5QQ19UWVBFX1FVRVNU",
            "EAIqqwEKCUVGb250VHlwZRITCg9FRk9OVF9UWVBFX05PTkUQABITCg9FRk9O",
            "VF9UWVBFX0hFQUwQARIZChVFRk9OVF9UWVBFX05PUk1BTF9ISVQQAhIbChdF",
            "Rk9OVF9UWVBFX0NSSVRJQ0FMX0hJVBADEhMKD0VGT05UX1RZUEVfR09MRBAE",
            "EhIKDkVGT05UX1RZUEVfRVhQEAUSEwoPRUZPTlRfVFlQRV9NSVNTEAYq9gIK",
            "DkVTa2lsbFNsb3RUeXBlEhkKFUVTS0lMTF9TTE9UX1RZUEVfTk9ORRAAEhsK",
            "F0VTS0lMTF9TTE9UX1RZUEVfTk9STUFMEAESGQoVRVNLSUxMX1NMT1RfVFlQ",
            "RV9EQVNIEAISHAoYRVNLSUxMX1NMT1RfVFlQRV9BQ1RJVkUxEAMSHAoYRVNL",
            "SUxMX1NMT1RfVFlQRV9BQ1RJVkUyEAQSHAoYRVNLSUxMX1NMT1RfVFlQRV9B",
            "Q1RJVkUzEAUSHAoYRVNLSUxMX1NMT1RfVFlQRV9BQ1RJVkU0EAYSHQoZRVNL",
            "SUxMX1NMT1RfVFlQRV9QQVNTSVZFMRAHEh0KGUVTS0lMTF9TTE9UX1RZUEVf",
            "UEFTU0lWRTIQCBIdChlFU0tJTExfU0xPVF9UWVBFX1BBU1NJVkUzEAkSHQoZ",
            "RVNLSUxMX1NMT1RfVFlQRV9QQVNTSVZFNBAKEh0KGUVTS0lMTF9TTE9UX1RZ",
            "UEVfUEFTU0lWRTUQCypjCg5FU2tpbGxBcmVhVHlwZRIZChVFU0tJTExfQVJF",
            "QV9UWVBFX05PTkUQABIbChdFU0tJTExfQVJFQV9UWVBFX1NJTkdMRRABEhkK",
            "FUVTS0lMTF9BUkVBX1RZUEVfQVJFQRACKoEBChVFU2tpbGxVc2FnZVRhcmdl",
            "dFR5cGUSIQodRVNLSUxMX1VTQUdFX1RBUkdFVF9UWVBFX1NFTEYQABIhCh1F",
            "U0tJTExfVVNBR0VfVEFSR0VUX1RZUEVfQUxMWRABEiIKHkVTS0lMTF9VU0FH",
            "RV9UQVJHRVRfVFlQRV9FTkVNWRACKoUBChNFU2tpbGxUYXJnZXRpbmdUeXBl",
            "EiQKIEVTS0lMTF9UQVJHRVRJTkdfVFlQRV9OT05fVEFSR0VUEAASIAocRVNL",
            "SUxMX1RBUkdFVElOR19UWVBFX1RBUkdFVBABEiYKIkVTS0lMTF9UQVJHRVRJ",
            "TkdfVFlQRV9TTUFSVF9UQVJHRVQQAipRChFFTW9uc3RlckFnZ3JvVHlwZRIe",
            "ChpFTU9OU1RFUl9BR0dST19UWVBFX01BTlVBTBAAEhwKGEVNT05TVEVSX0FH",
            "R1JPX1RZUEVfQVVUTxABQheqAhRHb29nbGUuUHJvdG9idWYuRW51bWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.EHeroClassType), typeof(global::Google.Protobuf.Enum.ECreateHeroResult), typeof(global::Google.Protobuf.Enum.EObjectType), typeof(global::Google.Protobuf.Enum.ECreatureState), typeof(global::Google.Protobuf.Enum.EMoveDir), typeof(global::Google.Protobuf.Enum.ESkillFailReason), typeof(global::Google.Protobuf.Enum.EStatType), typeof(global::Google.Protobuf.Enum.EMoveType), typeof(global::Google.Protobuf.Enum.EMonsterGrade), typeof(global::Google.Protobuf.Enum.ETeleportType), typeof(global::Google.Protobuf.Enum.EItemType), typeof(global::Google.Protobuf.Enum.EEquipItemType), typeof(global::Google.Protobuf.Enum.ESlotType), typeof(global::Google.Protobuf.Enum.EPickupFailReason), typeof(global::Google.Protobuf.Enum.EAddItemType), typeof(global::Google.Protobuf.Enum.EItemStatus), typeof(global::Google.Protobuf.Enum.EConsumableType), typeof(global::Google.Protobuf.Enum.EEffectType), typeof(global::Google.Protobuf.Enum.EEffectDurationType), typeof(global::Google.Protobuf.Enum.EEffectScalingType), typeof(global::Google.Protobuf.Enum.ESkillType), typeof(global::Google.Protobuf.Enum.ESkillProjectileType), typeof(global::Google.Protobuf.Enum.ENPCType), typeof(global::Google.Protobuf.Enum.EFontType), typeof(global::Google.Protobuf.Enum.ESkillSlotType), typeof(global::Google.Protobuf.Enum.ESkillAreaType), typeof(global::Google.Protobuf.Enum.ESkillUsageTargetType), typeof(global::Google.Protobuf.Enum.ESkillTargetingType), typeof(global::Google.Protobuf.Enum.EMonsterAggroType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EHeroClassType {
    [pbr::OriginalName("EHERO_CLASS_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EHERO_CLASS_TYPE_GUARDIAN")] Guardian = 1,
    [pbr::OriginalName("EHERO_CLASS_TYPE_ARCHER")] Archer = 2,
    [pbr::OriginalName("EHERO_CLASS_TYPE_MAGE")] Mage = 3,
  }

  public enum ECreateHeroResult {
    [pbr::OriginalName("ECREATE_HERO_RESULT_NONE")] None = 0,
    [pbr::OriginalName("ECREATE_HERO_RESULT_SUCCESS")] Success = 1,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_OVERLAP")] FailOverlap = 2,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_MINMAX")] FailMinmax = 3,
  }

  public enum EObjectType {
    [pbr::OriginalName("EOBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EOBJECT_TYPE_HERO")] Hero = 1,
    [pbr::OriginalName("EOBJECT_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("EOBJECT_TYPE_DROP_ITEM")] DropItem = 3,
    [pbr::OriginalName("EOBJECT_TYPE_NPC")] Npc = 4,
  }

  public enum ECreatureState {
    [pbr::OriginalName("ECREATURE_STATE_IDLE")] Idle = 0,
    [pbr::OriginalName("ECREATURE_STATE_MOVE")] Move = 1,
    [pbr::OriginalName("ECREATURE_STATE_SKILL")] Skill = 2,
    [pbr::OriginalName("ECREATURE_STATE_DIE")] Die = 3,
    [pbr::OriginalName("ECREATURE_STATE_HIT")] Hit = 4,
  }

  public enum EMoveDir {
    [pbr::OriginalName("EMOVE_DIR_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_DIR_UP")] Up = 1,
    [pbr::OriginalName("EMOVE_DIR_UP_RIGHT")] UpRight = 2,
    [pbr::OriginalName("EMOVE_DIR_RIGHT")] Right = 3,
    [pbr::OriginalName("EMOVE_DIR_RIGHT_DOWN")] RightDown = 4,
    [pbr::OriginalName("EMOVE_DIR_DOWN")] Down = 5,
    [pbr::OriginalName("EMOVE_DIR_DOWN_LEFT")] DownLeft = 6,
    [pbr::OriginalName("EMOVE_DIR_LEFT")] Left = 7,
    [pbr::OriginalName("EMOVE_DIR_LEFT_UP")] LeftUp = 8,
  }

  public enum ESkillFailReason {
    [pbr::OriginalName("ESKILL_FAIL_REASON_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_FAIL_REASON_STUN")] Stun = 1,
    [pbr::OriginalName("ESKILL_FAIL_REASON_DIST")] Dist = 2,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COST")] Cost = 3,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COOL")] Cool = 4,
  }

  public enum EStatType {
    [pbr::OriginalName("ESTAT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESTAT_TYPE_MAX_HP")] MaxHp = 1,
    [pbr::OriginalName("ESTAT_TYPE_MAX_MP")] MaxMp = 2,
    [pbr::OriginalName("ESTAT_TYPE_HP")] Hp = 3,
    [pbr::OriginalName("ESTAT_TYPE_MP")] Mp = 4,
    [pbr::OriginalName("ESTAT_TYPE_ATK")] Atk = 5,
    [pbr::OriginalName("ESTAT_TYPE_DEFENCE")] Defence = 6,
    [pbr::OriginalName("ESTAT_TYPE_MOVE_SPEED")] MoveSpeed = 7,
    [pbr::OriginalName("ESTAT_TYPE_ATK_SPEED")] AtkSpeed = 8,
    [pbr::OriginalName("ESTAT_TYPE_ADD_ATK_SPEED_MULTIPLIER")] AddAtkSpeedMultiplier = 9,
    [pbr::OriginalName("ESTAT_TYPE_BASE_ATK_SPEED")] BaseAtkSpeed = 10,
  }

  public enum EMoveType {
    [pbr::OriginalName("EMOVE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_TYPE_CHASE")] Chase = 1,
  }

  public enum EMonsterGrade {
    [pbr::OriginalName("EMONSTER_GRADE_NONE")] None = 0,
    [pbr::OriginalName("EMONSTER_GRADE_NORMAL")] Normal = 1,
    [pbr::OriginalName("EMONSTER_GRADE_RARE")] Rare = 2,
  }

  public enum ETeleportType {
    [pbr::OriginalName("ETELEPORT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ETELEPORT_TYPE_RESPAWN")] Respawn = 1,
  }

  public enum EItemType {
    [pbr::OriginalName("EITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EITEM_TYPE_EQUIP")] Equip = 1,
    [pbr::OriginalName("EITEM_TYPE_CONSUME")] Consume = 2,
    [pbr::OriginalName("EITEM_TYPE_ETC")] Etc = 3,
  }

  public enum EEquipItemType {
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_WEAPON")] Weapon = 1,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_SHIELD")] Shield = 2,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_HELMET")] Helmet = 3,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_ARMOR")] Armor = 4,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_BOOTS")] Boots = 5,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_GLOVES")] Gloves = 6,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_PENDANT")] Pendant = 7,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_RING")] Ring = 8,
  }

  public enum ESlotType {
    [pbr::OriginalName("ESLOT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESLOT_TYPE_WEAPON")] Weapon = 1,
    [pbr::OriginalName("ESLOT_TYPE_SHIELD")] Shield = 2,
    [pbr::OriginalName("ESLOT_TYPE_HELMET")] Helmet = 3,
    [pbr::OriginalName("ESLOT_TYPE_ARMOR")] Armor = 4,
    [pbr::OriginalName("ESLOT_TYPE_BOOTS")] Boots = 5,
    [pbr::OriginalName("ESLOT_TYPE_GLOVES")] Gloves = 6,
    [pbr::OriginalName("ESLOT_TYPE_PENDANT")] Pendant = 7,
    [pbr::OriginalName("ESLOT_TYPE_FIRST_RING")] FirstRing = 8,
    [pbr::OriginalName("ESLOT_TYPE_SECOND_RING")] SecondRing = 9,
    [pbr::OriginalName("ESLOT_TYPE_EQUIP")] Equip = 100,
    [pbr::OriginalName("ESLOT_TYPE_CONSUME")] Consume = 200,
    [pbr::OriginalName("ESLOT_TYPE_ETC")] Etc = 300,
  }

  public enum EPickupFailReason {
    [pbr::OriginalName("EPICKUP_FAIL_REASON_NONE")] None = 0,
    [pbr::OriginalName("EPICKUP_FAIL_REASON_NOT_MINE")] NotMine = 1,
    [pbr::OriginalName("EPICKUP_FAIL_REASON_FULL")] Full = 2,
  }

  public enum EAddItemType {
    [pbr::OriginalName("EADD_ITEM_TYPE_NEW")] New = 0,
    [pbr::OriginalName("EADD_ITEM_TYPE_OLD")] Old = 1,
  }

  public enum EItemStatus {
    [pbr::OriginalName("EITEM_STATUS_NONE")] None = 0,
    [pbr::OriginalName("EITEM_STATUS_EQUIPPED")] Equipped = 1,
  }

  public enum EConsumableType {
    [pbr::OriginalName("ECONSUMABLE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ECONSUMABLE_TYPE_HP")] Hp = 1,
    [pbr::OriginalName("ECONSUMABLE_TYPE_MP")] Mp = 2,
  }

  public enum EEffectType {
    [pbr::OriginalName("EEFFECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_TYPE_DAMAGE")] Damage = 1,
    [pbr::OriginalName("EEFFECT_TYPE_HEAL")] Heal = 2,
    [pbr::OriginalName("EEFFECT_TYPE_ADDSTAT")] Addstat = 3,
    [pbr::OriginalName("EEFFECT_TYPE_SHIELD")] Shield = 4,
    [pbr::OriginalName("EEFFECT_TYPE_AGGRO")] Aggro = 5,
  }

  public enum EEffectDurationType {
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_TEMPORARY")] Temporary = 1,
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_PERMANENT")] Permanent = 2,
  }

  public enum EEffectScalingType {
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_ATK")] Atk = 1,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_HP")] Hp = 2,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_ENTITY")] Entity = 3,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_MAXHP")] Maxhp = 4,
  }

  public enum ESkillType {
    [pbr::OriginalName("ESKILL_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_TYPE_ACTIVE")] Active = 1,
    [pbr::OriginalName("ESKILL_TYPE_PASSIVE")] Passive = 2,
  }

  public enum ESkillProjectileType {
    [pbr::OriginalName("ESKILL_PROJECTILE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_PROJECTILE_TYPE_PROJECTILE")] Projectile = 1,
  }

  public enum ENPCType {
    [pbr::OriginalName("ENPC_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ENPC_TYPE_STORE")] Store = 1,
    [pbr::OriginalName("ENPC_TYPE_QUEST")] Quest = 2,
  }

  public enum EFontType {
    [pbr::OriginalName("EFONT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EFONT_TYPE_HEAL")] Heal = 1,
    [pbr::OriginalName("EFONT_TYPE_NORMAL_HIT")] NormalHit = 2,
    [pbr::OriginalName("EFONT_TYPE_CRITICAL_HIT")] CriticalHit = 3,
    [pbr::OriginalName("EFONT_TYPE_GOLD")] Gold = 4,
    [pbr::OriginalName("EFONT_TYPE_EXP")] Exp = 5,
    [pbr::OriginalName("EFONT_TYPE_MISS")] Miss = 6,
  }

  public enum ESkillSlotType {
    [pbr::OriginalName("ESKILL_SLOT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_NORMAL")] Normal = 1,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_DASH")] Dash = 2,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE1")] Active1 = 3,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE2")] Active2 = 4,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE3")] Active3 = 5,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE4")] Active4 = 6,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE1")] Passive1 = 7,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE2")] Passive2 = 8,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE3")] Passive3 = 9,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE4")] Passive4 = 10,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE5")] Passive5 = 11,
  }

  public enum ESkillAreaType {
    [pbr::OriginalName("ESKILL_AREA_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_AREA_TYPE_SINGLE")] Single = 1,
    [pbr::OriginalName("ESKILL_AREA_TYPE_AREA")] Area = 2,
  }

  public enum ESkillUsageTargetType {
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_SELF")] Self = 0,
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_ALLY")] Ally = 1,
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_ENEMY")] Enemy = 2,
  }

  public enum ESkillTargetingType {
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_NON_TARGET")] NonTarget = 0,
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_TARGET")] Target = 1,
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_SMART_TARGET")] SmartTarget = 2,
  }

  public enum EMonsterAggroType {
    [pbr::OriginalName("EMONSTER_AGGRO_TYPE_MANUAL")] Manual = 0,
    [pbr::OriginalName("EMONSTER_AGGRO_TYPE_AUTO")] Auto = 1,
  }

  #endregion

}

#endregion Designer generated code
