// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqBAQoORUhlcm9DbGFzc1R5cGUSGQoV",
            "RUhFUk9fQ0xBU1NfVFlQRV9OT05FEAASHAoYRUhFUk9fQ0xBU1NfVFlQRV9X",
            "QVJSSU9SEAESGwoXRUhFUk9fQ0xBU1NfVFlQRV9BUkNIRVIQAhIZChVFSEVS",
            "T19DTEFTU19UWVBFX01BR0UQAyqdAQoRRUNyZWF0ZUhlcm9SZXN1bHQSHAoY",
            "RUNSRUFURV9IRVJPX1JFU1VMVF9OT05FEAASHwobRUNSRUFURV9IRVJPX1JF",
            "U1VMVF9TVUNDRVNTEAESJAogRUNSRUFURV9IRVJPX1JFU1VMVF9GQUlMX09W",
            "RVJMQVAQAhIjCh9FQ1JFQVRFX0hFUk9fUkVTVUxUX0ZBSUxfTUlOTUFYEANC",
            "F6oCFEdvb2dsZS5Qcm90b2J1Zi5FbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.EHeroClassType), typeof(global::Google.Protobuf.Enum.ECreateHeroResult), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EHeroClassType {
    [pbr::OriginalName("EHERO_CLASS_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EHERO_CLASS_TYPE_WARRIOR")] Warrior = 1,
    [pbr::OriginalName("EHERO_CLASS_TYPE_ARCHER")] Archer = 2,
    [pbr::OriginalName("EHERO_CLASS_TYPE_MAGE")] Mage = 3,
  }

  public enum ECreateHeroResult {
    [pbr::OriginalName("ECREATE_HERO_RESULT_NONE")] None = 0,
    [pbr::OriginalName("ECREATE_HERO_RESULT_SUCCESS")] Success = 1,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_OVERLAP")] FailOverlap = 2,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_MINMAX")] FailMinmax = 3,
  }

  #endregion

}

#endregion Designer generated code
