// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqBAQoORUhlcm9DbGFzc1R5cGUSGQoV",
            "RUhFUk9fQ0xBU1NfVFlQRV9OT05FEAASHAoYRUhFUk9fQ0xBU1NfVFlQRV9X",
            "QVJSSU9SEAESGwoXRUhFUk9fQ0xBU1NfVFlQRV9BUkNIRVIQAhIZChVFSEVS",
            "T19DTEFTU19UWVBFX01BR0UQAyqdAQoRRUNyZWF0ZUhlcm9SZXN1bHQSHAoY",
            "RUNSRUFURV9IRVJPX1JFU1VMVF9OT05FEAASHwobRUNSRUFURV9IRVJPX1JF",
            "U1VMVF9TVUNDRVNTEAESJAogRUNSRUFURV9IRVJPX1JFU1VMVF9GQUlMX09W",
            "RVJMQVAQAhIjCh9FQ1JFQVRFX0hFUk9fUkVTVUxUX0ZBSUxfTUlOTUFYEAMq",
            "cQoLRU9iamVjdFR5cGUSFQoRRU9CSkVDVF9UWVBFX05PTkUQABIVChFFT0JK",
            "RUNUX1RZUEVfSEVSTxABEhgKFEVPQkpFQ1RfVFlQRV9NT05TVEVSEAISGgoW",
            "RU9CSkVDVF9UWVBFX0RST1BfSVRFTRADKngKDkVDcmVhdHVyZVN0YXRlEhgK",
            "FEVDUkVBVFVSRV9TVEFURV9JRExFEAASGAoURUNSRUFUVVJFX1NUQVRFX01P",
            "VkUQARIZChVFQ1JFQVRVUkVfU1RBVEVfU0tJTEwQAhIXChNFQ1JFQVRVUkVf",
            "U1RBVEVfRElFEAMqzwEKCEVNb3ZlRGlyEhIKDkVNT1ZFX0RJUl9OT05FEAAS",
            "EAoMRU1PVkVfRElSX1VQEAESFgoSRU1PVkVfRElSX1VQX1JJR0hUEAISEwoP",
            "RU1PVkVfRElSX1JJR0hUEAMSGAoURU1PVkVfRElSX1JJR0hUX0RPV04QBBIS",
            "Cg5FTU9WRV9ESVJfRE9XThAFEhcKE0VNT1ZFX0RJUl9ET1dOX0xFRlQQBhIS",
            "Cg5FTU9WRV9ESVJfTEVGVBAHEhUKEUVNT1ZFX0RJUl9MRUZUX1VQEAgqhwEK",
            "CkVNb3ZlRm9yY2USFAoQRU1PVkVfRk9SQ0VfTk9ORRAAEhQKEEVNT1ZFX0ZP",
            "UkNFX1dFQUsQARIWChJFTU9WRV9GT1JDRV9OT1JNQUwQAhIdChlFTU9WRV9G",
            "T1JDRV9TTElHSFRfU1RST05HEAMSFgoSRU1PVkVfRk9SQ0VfU1RST05HEAQq",
            "awoKRVNraWxsVHlwZRIUChBFU0tJTExfVFlQRV9OT05FEAASFgoSRVNLSUxM",
            "X1RZUEVfTk9STUFMEAESFgoSRVNLSUxMX1RZUEVfQUNUSVZFEAISFwoTRVNL",
            "SUxMX1RZUEVfUEFTU0lWRRADKqMBChBFU2tpbGxGYWlsUmVhc29uEhsKF0VT",
            "S0lMTF9GQUlMX1JFQVNPTl9OT05FEAASGwoXRVNLSUxMX0ZBSUxfUkVBU09O",
            "X1NUVU4QARIbChdFU0tJTExfRkFJTF9SRUFTT05fRElTVBACEhsKF0VTS0lM",
            "TF9GQUlMX1JFQVNPTl9DT1NUEAMSGwoXRVNLSUxMX0ZBSUxfUkVBU09OX0NP",
            "T0wQBCrVAQoJRVN0YXRUeXBlEhMKD0VTVEFUX1RZUEVfTk9ORRAAEhUKEUVT",
            "VEFUX1RZUEVfTUFYX0hQEAESFQoRRVNUQVRfVFlQRV9NQVhfTVAQAhIRCg1F",
            "U1RBVF9UWVBFX0hQEAMSEQoNRVNUQVRfVFlQRV9NUBAEEhIKDkVTVEFUX1RZ",
            "UEVfQVRLEAUSFgoSRVNUQVRfVFlQRV9ERUZFTkNFEAYSGQoVRVNUQVRfVFlQ",
            "RV9NT1ZFX1NQRUVEEAcSGAoURVNUQVRfVFlQRV9BVEtfU1BFRUQQCCo2CglF",
            "TW92ZVR5cGUSEwoPRU1PVkVfVFlQRV9OT05FEAASFAoQRU1PVkVfVFlQRV9D",
            "SEFTRRABKlwKDUVNb25zdGVyR3JhZGUSFwoTRU1PTlNURVJfR1JBREVfTk9O",
            "RRAAEhkKFUVNT05TVEVSX0dSQURFX05PUk1BTBABEhcKE0VNT05TVEVSX0dS",
            "QURFX1JBUkUQAipECg1FVGVsZXBvcnRUeXBlEhcKE0VURUxFUE9SVF9UWVBF",
            "X05PTkUQABIaChZFVEVMRVBPUlRfVFlQRV9SRVNQQVdOEAEqYgoJRUl0ZW1U",
            "eXBlEhMKD0VJVEVNX1RZUEVfTk9ORRAAEhQKEEVJVEVNX1RZUEVfRVFVSVAQ",
            "ARIWChJFSVRFTV9UWVBFX0NPTlNVTUUQAhISCg5FSVRFTV9UWVBFX0VUQxAD",
            "KpACCg5FRXF1aXBJdGVtVHlwZRIZChVFRVFVSVBfSVRFTV9UWVBFX05PTkUQ",
            "ABIbChdFRVFVSVBfSVRFTV9UWVBFX1dFQVBPThABEhsKF0VFUVVJUF9JVEVN",
            "X1RZUEVfU0hJRUxEEAISGwoXRUVRVUlQX0lURU1fVFlQRV9IRUxNRVQQAxIa",
            "ChZFRVFVSVBfSVRFTV9UWVBFX0FSTU9SEAQSGgoWRUVRVUlQX0lURU1fVFlQ",
            "RV9CT09UUxAFEhsKF0VFUVVJUF9JVEVNX1RZUEVfR0xPVkVTEAYSHAoYRUVR",
            "VUlQX0lURU1fVFlQRV9QRU5EQU5UEAcSGQoVRUVRVUlQX0lURU1fVFlQRV9S",
            "SU5HEAhCF6oCFEdvb2dsZS5Qcm90b2J1Zi5FbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.EHeroClassType), typeof(global::Google.Protobuf.Enum.ECreateHeroResult), typeof(global::Google.Protobuf.Enum.EObjectType), typeof(global::Google.Protobuf.Enum.ECreatureState), typeof(global::Google.Protobuf.Enum.EMoveDir), typeof(global::Google.Protobuf.Enum.EMoveForce), typeof(global::Google.Protobuf.Enum.ESkillType), typeof(global::Google.Protobuf.Enum.ESkillFailReason), typeof(global::Google.Protobuf.Enum.EStatType), typeof(global::Google.Protobuf.Enum.EMoveType), typeof(global::Google.Protobuf.Enum.EMonsterGrade), typeof(global::Google.Protobuf.Enum.ETeleportType), typeof(global::Google.Protobuf.Enum.EItemType), typeof(global::Google.Protobuf.Enum.EEquipItemType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EHeroClassType {
    [pbr::OriginalName("EHERO_CLASS_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EHERO_CLASS_TYPE_WARRIOR")] Warrior = 1,
    [pbr::OriginalName("EHERO_CLASS_TYPE_ARCHER")] Archer = 2,
    [pbr::OriginalName("EHERO_CLASS_TYPE_MAGE")] Mage = 3,
  }

  public enum ECreateHeroResult {
    [pbr::OriginalName("ECREATE_HERO_RESULT_NONE")] None = 0,
    [pbr::OriginalName("ECREATE_HERO_RESULT_SUCCESS")] Success = 1,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_OVERLAP")] FailOverlap = 2,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_MINMAX")] FailMinmax = 3,
  }

  public enum EObjectType {
    [pbr::OriginalName("EOBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EOBJECT_TYPE_HERO")] Hero = 1,
    [pbr::OriginalName("EOBJECT_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("EOBJECT_TYPE_DROP_ITEM")] DropItem = 3,
  }

  public enum ECreatureState {
    [pbr::OriginalName("ECREATURE_STATE_IDLE")] Idle = 0,
    [pbr::OriginalName("ECREATURE_STATE_MOVE")] Move = 1,
    [pbr::OriginalName("ECREATURE_STATE_SKILL")] Skill = 2,
    [pbr::OriginalName("ECREATURE_STATE_DIE")] Die = 3,
  }

  public enum EMoveDir {
    [pbr::OriginalName("EMOVE_DIR_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_DIR_UP")] Up = 1,
    [pbr::OriginalName("EMOVE_DIR_UP_RIGHT")] UpRight = 2,
    [pbr::OriginalName("EMOVE_DIR_RIGHT")] Right = 3,
    [pbr::OriginalName("EMOVE_DIR_RIGHT_DOWN")] RightDown = 4,
    [pbr::OriginalName("EMOVE_DIR_DOWN")] Down = 5,
    [pbr::OriginalName("EMOVE_DIR_DOWN_LEFT")] DownLeft = 6,
    [pbr::OriginalName("EMOVE_DIR_LEFT")] Left = 7,
    [pbr::OriginalName("EMOVE_DIR_LEFT_UP")] LeftUp = 8,
  }

  public enum EMoveForce {
    [pbr::OriginalName("EMOVE_FORCE_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_FORCE_WEAK")] Weak = 1,
    [pbr::OriginalName("EMOVE_FORCE_NORMAL")] Normal = 2,
    [pbr::OriginalName("EMOVE_FORCE_SLIGHT_STRONG")] SlightStrong = 3,
    [pbr::OriginalName("EMOVE_FORCE_STRONG")] Strong = 4,
  }

  public enum ESkillType {
    [pbr::OriginalName("ESKILL_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_TYPE_NORMAL")] Normal = 1,
    [pbr::OriginalName("ESKILL_TYPE_ACTIVE")] Active = 2,
    [pbr::OriginalName("ESKILL_TYPE_PASSIVE")] Passive = 3,
  }

  public enum ESkillFailReason {
    [pbr::OriginalName("ESKILL_FAIL_REASON_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_FAIL_REASON_STUN")] Stun = 1,
    [pbr::OriginalName("ESKILL_FAIL_REASON_DIST")] Dist = 2,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COST")] Cost = 3,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COOL")] Cool = 4,
  }

  public enum EStatType {
    [pbr::OriginalName("ESTAT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESTAT_TYPE_MAX_HP")] MaxHp = 1,
    [pbr::OriginalName("ESTAT_TYPE_MAX_MP")] MaxMp = 2,
    [pbr::OriginalName("ESTAT_TYPE_HP")] Hp = 3,
    [pbr::OriginalName("ESTAT_TYPE_MP")] Mp = 4,
    [pbr::OriginalName("ESTAT_TYPE_ATK")] Atk = 5,
    [pbr::OriginalName("ESTAT_TYPE_DEFENCE")] Defence = 6,
    [pbr::OriginalName("ESTAT_TYPE_MOVE_SPEED")] MoveSpeed = 7,
    [pbr::OriginalName("ESTAT_TYPE_ATK_SPEED")] AtkSpeed = 8,
  }

  public enum EMoveType {
    [pbr::OriginalName("EMOVE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_TYPE_CHASE")] Chase = 1,
  }

  public enum EMonsterGrade {
    [pbr::OriginalName("EMONSTER_GRADE_NONE")] None = 0,
    [pbr::OriginalName("EMONSTER_GRADE_NORMAL")] Normal = 1,
    [pbr::OriginalName("EMONSTER_GRADE_RARE")] Rare = 2,
  }

  public enum ETeleportType {
    [pbr::OriginalName("ETELEPORT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ETELEPORT_TYPE_RESPAWN")] Respawn = 1,
  }

  public enum EItemType {
    [pbr::OriginalName("EITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EITEM_TYPE_EQUIP")] Equip = 1,
    [pbr::OriginalName("EITEM_TYPE_CONSUME")] Consume = 2,
    [pbr::OriginalName("EITEM_TYPE_ETC")] Etc = 3,
  }

  public enum EEquipItemType {
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_WEAPON")] Weapon = 1,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_SHIELD")] Shield = 2,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_HELMET")] Helmet = 3,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_ARMOR")] Armor = 4,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_BOOTS")] Boots = 5,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_GLOVES")] Gloves = 6,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_PENDANT")] Pendant = 7,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_RING")] Ring = 8,
  }

  #endregion

}

#endregion Designer generated code
